### ISSUE TITLE
Fatal error after clean installation

### ISSUE THREAD

**Issue by alexarcherr** [picocms/Pico#525]
Hello, I have a Fatal error after clean installation on Ubuntu 18.04

Apache 2.4
PHP 7.2

All dependencies installed: dom & mbstrins.

```
[Tue Jan 14 17:36:36.466384 2020] [php7:notice] [pid 12861] [client 213.128.197.1:55449] PHP Notice:  Undefined index: text in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 213
[Tue Jan 14 17:36:36.466484 2020] [php7:notice] [pid 12861] [client 213.128.197.1:55449] PHP Notice:  Undefined index: text in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 213
[Tue Jan 14 17:36:36.466698 2020] [php7:notice] [pid 12861] [client 213.128.197.1:55449] PHP Notice:  Undefined index: markup in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 232
[Tue Jan 14 17:36:36.466775 2020] [php7:warn] [pid 12861] [client 213.128.197.1:55449] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 483
[Tue Jan 14 17:36:36.466847 2020] [php7:error] [pid 12861] [client 213.128.197.1:55449] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMNode::removeChild() must be an instance of DOMNode, null given in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php:484\nStack trace:\n#0 /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php(484): DOMNode->removeChild(NULL)\n#1 /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php(232): ParsedownExtra->processTag('')\n#2 /var/www/alexarcher.me/vendor/erusev/parsedown/Parsedown.php(221): ParsedownExtra->blockMarkupComplete(Array)\n#3 /var/www/alexarcher.me/vendor/erusev/parsedown/Parsedown.php(52): Parsedown->linesElements(Array)\n#4 /var/www/alexarcher.me/vendor/erusev/parsedown/Parsedown.php(26): Parsedown->textElements('## Welcome to P...')\n#5 /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('\\n## Welcome to ...')\n#6 /var/www/alexarcher.me/vendor/picocms/pico/lib/Pico.php(1661): ParsedownExtra->text('\\n## Welcome to ...')\n#7 /var/www/alexarcher.me/vendor/picocms/pico/l in /var/www/alexarcher.me/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 484
```

**Comment by alexarcherr** [comment]
Was fixed when reinstalled from zip archive.

**Comment by mrbass21** [comment]
Just chiming in to say that I have the same setup and it's occurring for me too.

**Comment by qs5779** [comment]
clean install via composer same issue.

**Comment by smargo171** [comment]
same

**Comment by victortodoran** [comment]
why is this issue closed? This occurred after a clean composer install.

**Comment by PhrozenByte** [comment]
This issue isn't reproducible, sometimes Composer chooses to install an very old Pico 2.1.0 instead of the latest version. However, you can force Composer to install the latest version instead, fixing the issues reported. See https://github.com/picocms/Pico/issues/598#issuecomment-899044799
