### ISSUE TITLE
Map filter doesn't work as documented by Twig

### ISSUE THREAD

**Issue by dave-kennedy** [picocms/Pico#623]
According to the [Twig documentation](https://twig.symfony.com/doc/1.x/filters/map.html), this should work:

```
{% set people = [
    {first: "Bob", last: "Smith"},
    {first: "Alice", last: "Dupond"},
] %}

{{ people|map(p => "#{p.first} #{p.last}")|join(', ') }}
```

However this throws the following error:

```
[Sun Mar 20 23:32:27.248660 2022] [php:error] [pid 12] [client 172.17.0.1:64928] PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /var/www/localhost/htdocs/pico/vendor/picocms/pico/lib/PicoTwigExtension.php:285
Stack trace:
#0 /var/www/localhost/htdocs/pico/vendor/picocms/pico/lib/PicoTwigExtension.php(152): PicoTwigExtension::getKeyOfVar()
#1 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/Environment.php(497) : eval()'d code(40): PicoTwigExtension->mapFilter()
#2 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/Template.php(453): __TwigTemplate_5751ea7c50eca1750bc3952b6ce22d8d4c2142ae3b68d7ee69add82bb55ba61d->doDisplay()
#3 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/Template.php(420): Twig\\Template->displayWithErrorHandling()
#4 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/Template.php(432): Twig\\Template->display()
#5 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\\Template->render()
#6 /var/www/localhost/htdocs/pico/vendor/twig/twig/src/Environment.php(384): Twig\\TemplateWrapper->render()
#7 /var/www/localhost/htdocs/pico/vendor/picocms/pico/lib/Pico.php(514): Twig\\Environment->render()
#8 /var/www/localhost/htdocs/pico/index.php(33): Pico->run()
#9 {main}
  thrown in /var/www/localhost/htdocs/pico/vendor/picocms/pico/lib/PicoTwigExtension.php on line 285
```

It seems no matter what I pass to the `map` filter, it doesn't work as documented. I wonder if the filter is being replaced by Pico's own `map` filter, which works as described [here](https://picocms.org/docs/#twig-filters-and-functions):

> You can return all values of a given array key using the `map` filter (e.g. `{{ pages|map("title") }}` returns all page titles).

Is there another way I can access the Twig filter? I could really use it in a number of cases.

**Comment by dave-kennedy** [comment]
Okay, that's definitely what's happening. I deleted the `map` filter from PicoTwigExtension.php and magically got the desired behavior.

It's easy enough to get the Pico behavior using the Twig filter with something like `{{ pages | map(p => p.title }}` instead of `{{ pages | map('title') }}`. How difficult would it be to remove? Or maybe proxy the Twig filter in a backwards compatible way?

**Comment by PhrozenByte** [comment]
> I wonder if the filter is being replaced by Pico's own `map` filter

This is exactly the reason, Twig added this filter after we did. I'll remove it from Pico 3.0, since we're breaking BC anyway and it can be replaced by Twig's `map` filter (or the `column` filter for simple usages).

Just for the record: Twig 2 also introduced the `sort` filter as replacement for Pico's `sort_by` filter. Since the latter also supports a fallback and since it doesn't conflict with any of Twig's built-in filters, I'll leave it as-is for now.
